DROP TABLE IF EXISTS t_jw_xskb;
CREATE TABLE t_jw_xskb (
	id BIGINT(20) AUTO_INCREMENT PRIMARY KEY ,
	XN VARCHAR(100) NOT NULL COMMENT '学年	如，“2009”表示2009-2010学年',
	XQ_ID VARCHAR(100) NOT NULL COMMENT '学期ID	0第一学期，1第二学期，2第三学期',
	USER_KCDM VARCHAR(100) NOT NULL COMMENT '课程代码',
	KCMC VARCHAR(100) NOT NULL COMMENT '课程名称',
	SKBJ VARCHAR(100) NOT NULL COMMENT '上课班级',
	ZJJS_GH VARCHAR(100) NOT NULL COMMENT '教师工号',
	ZJJS_XM VARCHAR(100) NOT NULL COMMENT '教师姓名',
	STIMEZC VARCHAR(100) NOT NULL COMMENT '周次	如：1-5,8-18',
	DSZ VARCHAR(100) NOT NULL COMMENT '单双周	1单周，2双周，0全周',
	JCINFO VARCHAR(100) NOT NULL COMMENT '节次	如：1-2',
	ROOM VARCHAR(100) NOT NULL COMMENT '上课地点',
	USER_XH VARCHAR(100) NOT NULL COMMENT '学生学号',
	XM VARCHAR(100) NOT NULL COMMENT '学生姓名',
	JCZ VARCHAR(100) NOT NULL COMMENT '上课周	K12---1代表周一,2代表3-4节'
) ENGINE=InnoDB DEFAULT CHARSET = utf8;
ALTER TABLE `t_jw_xskb` ADD INDEX SCHEDULE_USER_XH USING HASH (`USER_XH`);
